[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-summary"
version = "0.1.0"
description = "A simple program to generate summary.json"
readme = "README.md"
license = {text = "GPL3Only"}
authors = [
    {name = "Moraxyc Xu", email = "i@qaq.li"},
]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "openai",
    'python-frontmatter',
]

[project.scripts]
ai-summary = "ai_summary.main:entry"

